#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
WRAPPER_PATH="$BIN_DIR/wmap"

echo "Setting up wmap in $SCRIPT_DIR"

if [ ! -d "$SCRIPT_DIR/venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$SCRIPT_DIR/venv"
else
    echo "Virtual environment already exists, reusing it."
fi

echo "Installing dependencies..."
"$SCRIPT_DIR/venv/bin/pip" install --quiet --upgrade pip
"$SCRIPT_DIR/venv/bin/pip" install --quiet -r "$SCRIPT_DIR/requirements.txt"

mkdir -p "$BIN_DIR"
cat > "$WRAPPER_PATH" << EOF
#!/usr/bin/env bash
# Auto-generated by install.sh runs wmap.py using its venv.
exec "$SCRIPT_DIR/venv/bin/python3" "$SCRIPT_DIR/wmap.py" "\$@"
EOF
chmod +x "$WRAPPER_PATH"

echo ""
echo "Done. wmap installed to $WRAPPER_PATH"

case ":$PATH:" in
    *":$BIN_DIR:"*)
        echo "You can now run: wmap <target>"
        ;;
    *)
        echo ""
        echo "NOTE: $BIN_DIR is not on your PATH."
        echo "Add this line to your ~/.bashrc or ~/.zshrc, then restart your terminal:"
        echo ""
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo ""
        ;;
esac
